name: Generate Assets

on:
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  Generate-Assets:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: iwansuryaningrat
          outputs: dist/snake.svg?palette=github-dark
          palette: github-dark

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: iwansuryaningrat

      - name: Check dist folder contents
        run: ls -R dist

      - name: Push assets to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
